// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRHD_FULL.Data;

#nullable disable

namespace PRHD_FULL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231006005442_change-casedto")]
    partial class changecasedto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("PRHD_FULL.Modelos.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EarliestPosiƟveOrderTestSampleCollectedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EarliestPosiƟveOrderTestType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderTestCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CaseId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("PRHD_FULL.Modelos.LaboratoryTest", b =>
                {
                    b.Property<string>("OrderTestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderTestResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderTestType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SampleCollectedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderTestId");

                    b.ToTable("LaboratoryTests");
                });
#pragma warning restore 612, 618
        }
    }
}
